#!/usr/bin/env python3
"""Generate deterministic Pydantic v2 protocol models from normalized IR."""

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

IR_HASH_PREFIX = "sha256:"
HEADER = """# AUTO-GENERATED by tools/generate_types.py -- DO NOT EDIT
# upstream: {upstream_crate} {upstream_version}
# ir_version: {ir_version}
# ir_hash: {ir_hash}

"""

RESERVED_WORDS = {
    "type",
    "class",
    "def",
    "import",
    "from",
    "pass",
    "return",
    "yield",
    "raise",
    "lambda",
    "with",
    "as",
    "global",
    "nonlocal",
    "assert",
    "del",
    "except",
    "finally",
    "try",
    "while",
    "for",
    "if",
    "elif",
    "else",
    "in",
    "not",
    "or",
    "and",
    "is",
}

# Top-level protocol enums that get their own files
TOP_LEVEL_ENUMS = {"Request", "Reply", "Response", "Event", "Action"}
# Inbound enums that support unknown sentinel fallback
INBOUND_ENUMS = {"Reply", "Event"}


def load_ir(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def compute_ir_hash(path: Path) -> str:
    return IR_HASH_PREFIX + hashlib.sha256(path.read_bytes()).hexdigest()


def ir_type_to_python(ir_type: str) -> str:
    if ir_type == "string":
        return "str"
    if ir_type == "integer":
        return "int"
    if ir_type == "float":
        return "float"
    if ir_type == "boolean":
        return "bool"
    if ir_type == "object":
        return "dict[str, Any]"
    if ir_type.startswith("option<"):
        inner = ir_type[7:-1]
        inner_py = ir_type_to_python(inner)
        return f"{inner_py} | None"
    if ir_type.startswith("array<"):
        inner = ir_type[6:-1]
        inner_py = ir_type_to_python(inner)
        return f"list[{inner_py}]"
    if ir_type.startswith("map<"):
        parts = ir_type[4:-1].split(",", 1)
        val_py = ir_type_to_python(parts[1].strip()) if len(parts) > 1 else "Any"
        return f"dict[str, {val_py}]"
    if ir_type.startswith("ref:"):
        name = ir_type[4:]
        if name == "Unknown":
            return "Any"
        return name
    return "Any"


def safe_field_name(name: str) -> str:
    if name in RESERVED_WORDS:
        return f"{name}_"
    return name


def variant_class_name(variant_name: str, enum_name: str) -> str:
    name = f"{variant_name}{enum_name}"
    if name[0].isdigit():
        name = f"_{name}"
    return name


def gen_struct_code(ir_type: dict) -> str:
    lines = []
    fields = ir_type.get("fields", [])
    lines.append(f"class {ir_type['name']}(BaseModel):")
    lines.append("    model_config = ConfigDict(populate_by_name=True, strict=False)")
    if fields:
        for f in fields:
            py_type = ir_type_to_python(f["type"])
            field_name = safe_field_name(f["name"])
            if f["required"]:
                lines.append(f"    {field_name}: {py_type}")
            else:
                lines.append(f"    {field_name}: {py_type} = None")
    else:
        lines.append("    pass")
    return "\n".join(lines)


def gen_variant_code(variant: dict, enum_name: str) -> str:
    var_name = variant["name"]
    cls_name = variant_class_name(var_name, enum_name)
    kind = variant["kind"]
    lines = [f"class {cls_name}(BaseModel):"]

    if kind == "unit":
        lines.append("    pass")
    elif kind == "newtype":
        inner = variant.get("inner_type", "string")
        py_type = ir_type_to_python(inner)
        lines.append(f"    payload: {py_type}")
    elif kind == "struct":
        fields = variant.get("fields", [])
        if not fields:
            lines.append("    pass")
        else:
            for f in fields:
                py_type = ir_type_to_python(f["type"])
                field_name = safe_field_name(f["name"])
                if f["required"]:
                    lines.append(f"    {field_name}: {py_type}")
                else:
                    lines.append(f"    {field_name}: {py_type} = None")
    return "\n".join(lines)


def gen_unknown_sentinel_code(enum_name: str) -> str:
    cls_name = f"Unknown{enum_name}"
    return f"""
class {cls_name}(BaseModel):
    variant_name: str
    raw_payload: Any
"""


def gen_enum_code(enum_name: str, variants: list[dict], has_unknown: bool) -> str:
    lines = []
    unknown_cls = f"Unknown{enum_name}"
    var_table = f"_{enum_name.upper()}_VARIANTS"
    name_table = f"_{enum_name.upper()}_VARIANT_NAMES"

    lines.append("")
    lines.append(f"# Wire-name to variant class mapping")
    lines.append(f"{var_table}: dict[str, type[BaseModel]] = {{")
    for v in variants:
        cls = variant_class_name(v["name"], enum_name)
        lines.append(f'    "{v["name"]}": {cls},')
    lines.append("}")
    lines.append("")
    lines.append(f"# Variant class to wire-name mapping")
    lines.append(f"{name_table}: dict[type[BaseModel], str] = {{")
    for v in variants:
        cls = variant_class_name(v["name"], enum_name)
        lines.append(f'    {cls}: "{v["name"]}",')
    lines.append("}")
    lines.append("")

    variant_classes = [variant_class_name(v["name"], enum_name) for v in variants]
    if has_unknown:
        variant_classes.append(unknown_cls)
    union_str = " | ".join(variant_classes)

    lines.append(f"class {enum_name}(BaseModel):")
    lines.append("    model_config = ConfigDict(populate_by_name=True, strict=False)")
    lines.append(f"    variant: {union_str}")
    lines.append("")
    lines.append('    @model_validator(mode="before")')
    lines.append("    @classmethod")
    lines.append("    def _decode_external_tag(cls, data: Any) -> dict[str, Any]:")
    lines.append("        from niri_pypc.types.codec import decode_externally_tagged")
    if has_unknown:
        lines.append(f'        return {{"variant": decode_externally_tagged(')
        lines.append(f"            data, {var_table},")
        lines.append(f"            unknown_sentinel={unknown_cls},")
        lines.append("        )}")
    else:
        lines.append(f'        return {{"variant": decode_externally_tagged(data, {var_table})}}')
    lines.append("")
    lines.append("    @model_serializer")
    lines.append("    def _encode_external_tag(self) -> Any:")
    lines.append("        from niri_pypc.types.codec import encode_externally_tagged")
    lines.append(f"        return encode_externally_tagged(self.variant, {name_table})")

    return "\n".join(lines)


def write_file(path: Path, content: str, ir: dict, ir_hash: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(
            HEADER.format(
                upstream_crate=ir["upstream_crate"],
                upstream_version=ir["upstream_version"],
                ir_version=ir["ir_version"],
                ir_hash=ir_hash,
            )
        )
        f.write(content)


def main():
    parser = argparse.ArgumentParser(description="Generate Pydantic models from IR")
    parser.add_argument("--ir", default="schema/ir/niri-ipc-ir.json")
    parser.add_argument("--output-dir", default="src/niri_pypc/types/generated/")
    args = parser.parse_args()

    ir_path = Path(args.ir)
    output_dir = Path(args.output_dir)

    ir = load_ir(ir_path)
    ir_hash = compute_ir_hash(ir_path)
    ir_types = ir["types"]

    types_by_name: dict[str, dict] = {t["name"]: t for t in ir_types}

    # ---- _metadata.py ----
    meta_lines = [
        'UPSTREAM_CRATE: str = "{}"'.format(ir["upstream_crate"]),
        'UPSTREAM_VERSION: str = "{}"'.format(ir["upstream_version"]),
        'GENERATOR_VERSION: str = "1"',
        'IR_VERSION: str = "{}"'.format(ir["ir_version"]),
        'IR_HASH: str = "{}"'.format(ir_hash),
        "SCHEMA_HASHES: dict[str, str] = {",
    ]
    for key, h in ir["schema_hashes"].items():
        meta_lines.append(f'    "{key}": "{h}",')
    meta_lines.append("}")
    write_file(output_dir / "_metadata.py", "\n".join(meta_lines) + "\n", ir, ir_hash)

    # ---- models.py: all structs + helper enums ----
    models_lines = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "from pydantic import BaseModel, ConfigDict, model_validator, model_serializer",
        "",
    ]

    for t in ir_types:
        if t["name"] in TOP_LEVEL_ENUMS:
            continue
        if t["kind"] == "struct":
            models_lines.append("")
            models_lines.append(gen_struct_code(t))
        elif t["kind"] == "enum":
            has_unknown = False
            # Variant classes
            for v in t["variants"]:
                models_lines.append("")
                models_lines.append(gen_variant_code(v, t["name"]))
            # Root enum
            models_lines.append(gen_enum_code(t["name"], t["variants"], has_unknown))

    write_file(output_dir / "models.py", "\n".join(models_lines) + "\n", ir, ir_hash)

    # ---- Top-level enum files ----
    enum_file_map = {
        "action.py": ["Action"],
        "event.py": ["Event"],
        "request.py": ["Request"],
        "reply.py": ["Reply", "Response"],
    }

    # Map top-level enum names to their files
    enum_to_file = {}
    for fname, enames in enum_file_map.items():
        for en in enames:
            enum_to_file[en] = fname.replace(".py", "")

    for filename, enum_names in enum_file_map.items():
        lines = [
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "from pydantic import BaseModel, ConfigDict, model_validator, model_serializer",
        ]

        # Collect referenced types
        refs = set()
        for enum_name in enum_names:
            t = types_by_name.get(enum_name)
            if t and t["kind"] == "enum":
                for v in t["variants"]:
                    _collect_refs_from_variant(v, refs)

        # Filter refs to those that exist and are not in the same file
        same_file = set(enum_names)
        refs = {r for r in refs if r in types_by_name and r not in same_file}

        # Group refs by which module they come from
        models_refs = set()
        top_refs: dict[str, set[str]] = {}
        for r in refs:
            if r in enum_to_file:
                mod = enum_to_file[r]
                if mod not in top_refs:
                    top_refs[mod] = set()
                top_refs[mod].add(r)
            else:
                models_refs.add(r)

        # Import from models.py
        if models_refs:
            lines.append("from niri_pypc.types.generated.models import (")
            for r in sorted(models_refs):
                lines.append(f"    {r},")
            lines.append(")")

        # Import from other top-level enum files
        for mod, names in sorted(top_refs.items()):
            lines.append(f"from niri_pypc.types.generated.{mod} import (")
            for r in sorted(names):
                lines.append(f"    {r},")
            lines.append(")")

        lines.append("")

        for enum_name in enum_names:
            t = types_by_name.get(enum_name)
            if t and t["kind"] == "enum":
                has_unknown = enum_name in INBOUND_ENUMS
                for v in t["variants"]:
                    lines.append("")
                    lines.append(gen_variant_code(v, enum_name))
                if has_unknown:
                    lines.append("")
                    lines.append(gen_unknown_sentinel_code(enum_name))
                lines.append(gen_enum_code(enum_name, t["variants"], has_unknown))

        write_file(output_dir / filename, "\n".join(lines) + "\n", ir, ir_hash)

    # ---- __init__.py ----
    init_lines = [
        "from niri_pypc.types.generated._metadata import *  # noqa: F401,F403",
    ]
    for fname in ["models.py", "action.py", "event.py", "request.py", "reply.py"]:
        init_lines.append(f"from niri_pypc.types.generated.{fname.replace('.py', '')} import *  # noqa: F401,F403")
    write_file(output_dir / "__init__.py", "\n".join(init_lines) + "\n", ir, ir_hash)

    print(f"Generated types in {output_dir}")


def _collect_refs_from_variant(v: dict, refs: set[str]) -> None:
    if v["kind"] == "newtype":
        _extract_refs_from_type(v.get("inner_type", ""), refs)
    elif v["kind"] == "struct":
        for f in v.get("fields", []):
            _extract_refs_from_type(f["type"], refs)


def _extract_refs_from_type(t: str, refs: set[str]) -> None:
    if t.startswith("ref:"):
        refs.add(t[4:])
    elif t.startswith("option<ref:"):
        refs.add(t[11:-1])
    elif t.startswith("array<ref:"):
        refs.add(t[10:-1])


if __name__ == "__main__":
    main()
