#!/usr/bin/env python3
"""Generate deterministic Pydantic v2 protocol models from normalized IR."""

import argparse
import hashlib
import json
from pathlib import Path

IR_HASH_PREFIX = "sha256:"
HEADER = """# AUTO-GENERATED by tools/generate_types.py -- DO NOT EDIT
# upstream: {upstream_crate} {upstream_version}
# ir_version: {ir_version}
# ir_hash: {ir_hash}

"""

RESERVED_WORDS = {
    "type",
    "class",
    "def",
    "import",
    "from",
    "pass",
    "return",
    "yield",
    "raise",
    "lambda",
    "with",
    "as",
    "global",
    "nonlocal",
    "assert",
    "del",
    "except",
    "finally",
    "try",
    "while",
    "for",
    "if",
    "elif",
    "else",
    "in",
    "not",
    "or",
    "and",
    "is",
}

TOP_LEVEL_ENUMS = {"Request", "Reply", "Response", "Event", "Action"}
INBOUND_ENUMS = {"Event"}


def load_ir(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def compute_ir_hash(path: Path) -> str:
    return IR_HASH_PREFIX + hashlib.sha256(path.read_bytes()).hexdigest()


def ir_type_to_python(ir_type: str) -> str:
    if ir_type == "string":
        return "str"
    if ir_type == "integer":
        return "int"
    if ir_type == "float":
        return "float"
    if ir_type == "boolean":
        return "bool"
    if ir_type == "object":
        return "dict[str, Any]"
    if ir_type.startswith("option<"):
        inner = ir_type[7:-1]
        inner_py = ir_type_to_python(inner)
        return f"{inner_py} | None"
    if ir_type.startswith("array<"):
        inner = ir_type[6:-1]
        inner_py = ir_type_to_python(inner)
        return f"list[{inner_py}]"
    if ir_type.startswith("map<"):
        parts = ir_type[4:-1].split(",", 1)
        val_py = ir_type_to_python(parts[1].strip()) if len(parts) > 1 else "Any"
        return f"dict[str, {val_py}]"
    if ir_type.startswith("tuple<"):
        inner = ir_type[6:-1]
        parts = inner.split(",")
        py_types = [ir_type_to_python(p.strip()) for p in parts]
        return f"tuple[{', '.join(py_types)}]"
    if ir_type.startswith("ref:"):
        name = ir_type[4:]
        if name == "Unknown":
            return "Any"
        return name
    return "Any"


def safe_field_name(name: str) -> str:
    if name in RESERVED_WORDS:
        return f"{name}_"
    return name


def variant_class_name(variant_name: str, enum_name: str) -> str:
    name = f"{variant_name}{enum_name}"
    if name[0].isdigit():
        name = f"_{name}"
    return name


def safe_enum_member_name(name: str) -> str:
    candidate = name.upper().replace("-", "_")
    if candidate[0].isdigit():
        candidate = f"VALUE_{candidate}"
    if candidate in RESERVED_WORDS:
        candidate = f"{candidate}_"
    return candidate


def is_all_unit_enum(ir_type: dict) -> bool:
    return ir_type["kind"] == "enum" and all(v["kind"] == "unit" for v in ir_type["variants"])


def gen_struct_code(ir_type: dict) -> str:
    lines = [f"class {ir_type['name']}(ProtocolModel):"]
    fields = ir_type.get("fields", [])
    if not fields:
        lines.append("    pass")
        return "\n".join(lines)

    for f in fields:
        py_type = ir_type_to_python(f["type"])
        field_name = safe_field_name(f["name"])
        if f["required"]:
            lines.append(f"    {field_name}: {py_type}")
        else:
            lines.append(f"    {field_name}: {py_type} = None")
    return "\n".join(lines)


def gen_variant_code(variant: dict, enum_name: str) -> str:
    var_name = variant["name"]
    cls_name = variant_class_name(var_name, enum_name)
    kind = variant["kind"]
    lines = [
        f"class {cls_name}(ProtocolVariant):",
        f'    __niri_wire_name__ = "{var_name}"',
        f'    __niri_variant_kind__ = "{kind}"',
    ]

    if kind == "unit":
        lines.append("    pass")
    elif kind == "newtype":
        inner = variant.get("inner_type", "string")
        py_type = ir_type_to_python(inner)
        lines.append(f"    payload: {py_type}")
    elif kind == "struct":
        fields = variant.get("fields", [])
        if not fields:
            lines.append("    pass")
        else:
            for f in fields:
                py_type = ir_type_to_python(f["type"])
                field_name = safe_field_name(f["name"])
                if f["required"]:
                    lines.append(f"    {field_name}: {py_type}")
                else:
                    lines.append(f"    {field_name}: {py_type} = None")

    return "\n".join(lines)


def gen_all_unit_str_enum_code(ir_type: dict) -> str:
    """Generate a StrEnum for all-unit enums like Transform, Layer, etc."""
    lines = ["class StrEnum(str, enum.Enum):", "    pass", ""]
    # We need to generate the actual StrEnum subclass
    lines = [f"class {ir_type['name']}(StrEnum):"]
    for v in ir_type["variants"]:
        member_name = safe_enum_member_name(v["name"])
        lines.append(f'    {member_name} = "{v["name"]}"')
    return "\n".join(lines)


def gen_externally_tagged_wrapper_code(enum_name: str, variants: list[dict], has_unknown: bool) -> str:
    """Generate a union alias + ExternallyTaggedEnum subclass."""
    unknown_cls = f"Unknown{enum_name}"
    variant_classes = [variant_class_name(v["name"], enum_name) for v in variants]
    if has_unknown:
        variant_classes.append(unknown_cls)
    union_str = " | ".join(variant_classes)

    has_unknown_base_import = enum_name == "Event"

    lines = [""]
    lines.append(f"{enum_name}Value: TypeAlias = {union_str}")
    lines.append("")

    lines.append(f"class {enum_name}(ExternallyTaggedEnum[{enum_name}Value]):")
    lines.append("    __niri_variants__ = (")
    for v in variants:
        cls = variant_class_name(v["name"], enum_name)
        lines.append(f"        {cls},")
    lines.append("    )")
    if has_unknown:
        if has_unknown_base_import:
            lines.append("    __niri_unknown_variant_model__ = UnknownEvent")
        else:
            lines.append(f"    __niri_unknown_variant_model__ = {unknown_cls}")

    return "\n".join(lines)


def gen_reply_unwrap_code() -> str:
    return """
    def unwrap(self) -> ResponseValue:
        if isinstance(self.root, OkReply):
            return self.root.payload.root

        if isinstance(self.root, ErrReply):
            raise RemoteError(
                f"Compositor error: {self.root.payload}",
                operation="Reply.unwrap",
                remote_message=self.root.payload,
            )

        raise DecodeError(
            f"Unexpected reply variant: {type(self.root).__name__}",
            operation="Reply.unwrap",
        )
"""


def gen_unknown_sentinel_code(enum_name: str) -> str:
    """Generate UnknownEvent/UnknownReply sentinel."""
    cls_name = f"Unknown{enum_name}"
    lines = [
        "",
        f"class {cls_name}(ProtocolModel):",
        "    variant_name: str",
        "    raw_payload: Any",
    ]
    return "\n".join(lines)


def write_file(path: Path, content: str, ir: dict, ir_hash: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(
            HEADER.format(
                upstream_crate=ir["upstream_crate"],
                upstream_version=ir["upstream_version"],
                ir_version=ir["ir_version"],
                ir_hash=ir_hash,
            )
        )
        f.write(content)


def main():
    parser = argparse.ArgumentParser(description="Generate Pydantic models from IR")
    parser.add_argument("--ir", default="schema/ir/niri-ipc-ir.json")
    parser.add_argument("--output-dir", default="src/niri_pypc/types/generated/")
    args = parser.parse_args()

    ir_path = Path(args.ir)
    output_dir = Path(args.output_dir)

    ir = load_ir(ir_path)
    ir_hash = compute_ir_hash(ir_path)
    ir_types = ir["types"]

    types_by_name: dict[str, dict] = {t["name"]: t for t in ir_types}

    # ---- _metadata.py ----
    meta_lines = [
        'UPSTREAM_CRATE: str = "{}"'.format(ir["upstream_crate"]),
        'UPSTREAM_VERSION: str = "{}"'.format(ir["upstream_version"]),
        'GENERATOR_VERSION: str = "2"',
        'IR_VERSION: str = "{}"'.format(ir["ir_version"]),
        f'IR_HASH: str = "{ir_hash}"',
        "SCHEMA_HASHES: dict[str, str] = {",
    ]
    for key, h in ir["schema_hashes"].items():
        meta_lines.append(f'    "{key}": "{h}",')
    meta_lines.append("}")
    write_file(output_dir / "_metadata.py", "\n".join(meta_lines) + "\n", ir, ir_hash)

    # ---- models.py: all structs + helper enums ----
    # Import block: base types, plus StrEnum for all-unit enums
    models_header = """from __future__ import annotations

from enum import StrEnum
from typing import Any, TypeAlias

from niri_pypc.types.base import ExternallyTaggedEnum, ProtocolModel, ProtocolVariant

"""
    models_lines = [models_header]

    for t in ir_types:
        if t["name"] in TOP_LEVEL_ENUMS:
            continue
        if t["kind"] == "struct":
            models_lines.append("")
            models_lines.append(gen_struct_code(t))
        elif t["kind"] == "enum":
            if is_all_unit_enum(t):
                models_lines.append("")
                models_lines.append(gen_all_unit_str_enum_code(t))
            else:
                has_unknown = t["name"] in INBOUND_ENUMS
                for v in t["variants"]:
                    models_lines.append("")
                    models_lines.append(gen_variant_code(v, t["name"]))
                if has_unknown:
                    models_lines.append(gen_unknown_sentinel_code(t["name"]))
                models_lines.append(gen_externally_tagged_wrapper_code(t["name"], t["variants"], has_unknown))

    # Rebuild all non-unit-enum models in models.py to resolve forward references
    for t in ir_types:
        if t["name"] in TOP_LEVEL_ENUMS:
            continue
        if t["kind"] == "struct":
            models_lines.append(f"{t['name']}.model_rebuild()")
        elif t["kind"] == "enum" and not is_all_unit_enum(t):
            models_lines.append(f"{t['name']}.model_rebuild()")
        # No need to rebuild variant classes - they're rebuilt when their parent enum is rebuilt

    write_file(output_dir / "models.py", "\n".join(models_lines) + "\n", ir, ir_hash)

    # ---- Top-level enum files ----
    enum_file_map = {
        "action.py": ["Action"],
        "event.py": ["Event"],
        "request.py": ["Request"],
        "reply.py": ["Response", "Reply"],
    }

    enum_to_file = {}
    for fname, enames in enum_file_map.items():
        for en in enames:
            enum_to_file[en] = fname.replace(".py", "")

    for filename, enum_names in enum_file_map.items():
        needs_reply_unwrap = "Reply" in enum_names
        needs_unknown_event = "Event" in enum_names

        # Build import lines
        import_lines = [
            "from __future__ import annotations",
            "",
            "from typing import TypeAlias",
        ]

        base_imports = ["ExternallyTaggedEnum", "ProtocolVariant"]
        if needs_unknown_event:
            base_imports.append("ProtocolModel")
            base_imports.append("UnknownEvent")
        import_lines.append(f"from niri_pypc.types.base import {', '.join(base_imports)}")

        if needs_reply_unwrap:
            import_lines.append("from niri_pypc.errors import DecodeError, RemoteError")

        # Collect referenced types
        refs = set()
        for enum_name in enum_names:
            t = types_by_name.get(enum_name)
            if t and t["kind"] == "enum":
                for v in t["variants"]:
                    _collect_refs_from_variant(v, refs)

        same_file = set(enum_names)
        refs = {r for r in refs if r in types_by_name and r not in same_file}

        models_refs = set()
        top_refs: dict[str, set[str]] = {}
        for r in refs:
            if r in enum_to_file:
                mod = enum_to_file[r]
                if mod not in top_refs:
                    top_refs[mod] = set()
                top_refs[mod].add(r)
            else:
                models_refs.add(r)

        if models_refs:
            import_lines.append("from niri_pypc.types.generated.models import (")
            for r in sorted(models_refs):
                import_lines.append(f"    {r},")
            import_lines.append(")")

        for mod, names in sorted(top_refs.items()):
            import_lines.append(f"from niri_pypc.types.generated.{mod} import (")
            for r in sorted(names):
                import_lines.append(f"    {r},")
            import_lines.append(")")

        # Build body lines
        body_lines = list(import_lines)
        body_lines.append("")

        rebuilds = []
        for enum_name in enum_names:
            t = types_by_name.get(enum_name)
            if t and t["kind"] == "enum":
                if not is_all_unit_enum(t):
                    has_unknown = enum_name in INBOUND_ENUMS
                    for v in t["variants"]:
                        body_lines.append("")
                        body_lines.append(gen_variant_code(v, enum_name))
                    body_lines.append(gen_externally_tagged_wrapper_code(enum_name, t["variants"], has_unknown))
                    rebuilds.append(enum_name)

                    if filename == "reply.py" and enum_name == "Reply":
                        body_lines[-1] = body_lines[-1] + gen_reply_unwrap_code()

        # Rebuild all ExternallyTaggedEnum wrappers to resolve forward references
        for name in rebuilds:
            body_lines.append(f"{name}.model_rebuild()")

        write_file(output_dir / filename, "\n".join(body_lines) + "\n", ir, ir_hash)

    # ---- __init__.py ----
    init_lines = [
        "from niri_pypc.types.generated._metadata import *  # noqa: F401,F403",
    ]
    for fname in ["models.py", "action.py", "event.py", "request.py", "reply.py"]:
        init_lines.append(f"from niri_pypc.types.generated.{fname.replace('.py', '')} import *  # noqa: F401,F403")
    write_file(output_dir / "__init__.py", "\n".join(init_lines) + "\n", ir, ir_hash)

    print(f"Generated types in {output_dir}")


def _collect_refs_from_variant(v: dict, refs: set[str]) -> None:
    if v["kind"] == "newtype":
        _extract_refs_from_type(v.get("inner_type", ""), refs)
    elif v["kind"] == "struct":
        for f in v.get("fields", []):
            _extract_refs_from_type(f["type"], refs)


def _extract_refs_from_type(t: str, refs: set[str]) -> None:
    if t.startswith("ref:"):
        name = t[4:]
        if name != "Unknown":
            refs.add(name)
    elif t.startswith("option<"):
        _extract_refs_from_type(t[7:-1], refs)
    elif t.startswith("array<"):
        _extract_refs_from_type(t[6:-1], refs)
    elif t.startswith("map<"):
        parts = t[4:-1].split(",", 1)
        if len(parts) > 1:
            _extract_refs_from_type(parts[1].strip(), refs)
    elif t.startswith("tuple<"):
        inner = t[6:-1]
        for part in inner.split(","):
            _extract_refs_from_type(part.strip(), refs)


if __name__ == "__main__":
    main()
